spring.application.name=demo

# ===============================
# CONFIGURAÇÃO DO POSTGRESQL
# ===============================
spring.datasource.url=jdbc:postgresql://localhost:5432/sistema_projetos
spring.datasource.username=postgres
spring.datasource.password=senha
spring.datasource.driver-class-name=org.postgresql.Driver

# ===============================
# CONFIGURAÇÃO DO HIBERNATE (JPA)
# ===============================
# A mágica que cria as tabelas automaticamente
spring.jpa.hibernate.ddl-auto=update

# Mostra no console os comandos SQL que o Spring está fazendo por trás dos panos (ótimo para aprender)
spring.jpa.show-sql=true
spring.jpa.properties.hibernate.format_sql=true
